# Generated by Django 3.2.1 on 2021-05-07 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDataText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField(default=None)),
            ],
        ),
        migrations.RenameModel(
            old_name='RequestData',
            new_name='RequestDataJson',
        ),
    ]
